class Employee {
  constructor(id, fullName, age, contact, department,referralCode) {
    this.id = id; // represents the id generated by the firestore
    this.fullName = fullName;
    this.age = age;
    this.contact = contact;
    this.department = department;
    this.url = url;
    this.referralCode = referralCode;
    
  }
}

module.exports = Employee;
